# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='django-flexible-forms',
    version='0.1.0',
    description='A reusable Django app for managing database-backed  forms.',
    python_requires='==3.*,>=3.8.0',
    author='Eric Abruzzese',
    author_email='eric.abruzzese@gmail.com',
    license='MIT',
    packages=['flexible_forms'],
    package_dir={"flexible_forms": "."},
    package_data={},
    install_requires=[
        'django>=2.2', 'pillow==7.*,>=7.2.0', 'psycopg2-binary==2.*,>=2.8.5',
        'swapper==1.*,>=1.1.2'
    ],
    extras_require={
        "dev": [
            "autopep8==1.*,>=1.5.4", "django-stubs==1.*,>=1.5.0",
            "factory-boy==3.*,>=3.0.1", "hypothesis[django]==5.*,>=5.26.0",
            "isort==5.*,>=5.4.2", "mypy>=0.770", "pytest==6.*,>=6.0.1"
        ]
    },
)
